version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: mobiliza
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "8082:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mobiliza-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mobiliza_backend
    ports:
      - "8081:8081"
    env_file:
      - app.env
    depends_on:
      - postgres
    networks:
      - mobiliza-network

volumes:
  postgres_data:

networks:
  mobiliza-network:
    driver: bridge
